### PR TITLE
Add project assets

### PR DESCRIPTION
**Pull request by AlexejheroYTB**

### CODE REVIEW

**Comment by AlexejheroYTB** [comment]
Any other assets that would be useful to have in the repo?

**Comment by kylinator25** [comment]
Do we have somewhere we can put misc files that would be useful to mod authors? Is this just for QMod specific assets?

**Comment by AlexejheroYTB** [comment]
Explaing `misc files` please.

**Comment by kylinator25** [comment]
Stuff like ingame prefab lists, just to put it all in an accessible place rather than modders having to dig through game files

**Comment by AlexejheroYTB** [comment]
This pull request is just about QModManager specific assets.

**Pull request merged**
