### PR TITLE
Mac installer

### PR DESCRIPTION
**Pull request by legojoshua12**
Adds the mac installer to the Mac Installation folder and removes the old stuff

### CODE REVIEW

**Comment by AlexejheroYTB** [comment]
I will wait for all of the 2.0 prs to be closed before merging the mac installer, seeing as it might need to be updated

**Comment by AlexejheroYTB** [comment]
On hold until we release 2.0.1

**Comment by legojoshua12** [comment]
Hold off on the merge, something is horribly broken in below zero on start

**Comment by PrimeSonic** [comment]
There hasn't been any activity on the PR for over a month.  
Is it still actively being worked on?

**Comment by AlexejheroYTB** [comment]
There is an issue with the Below Zero install, I would suggest waiting until 2.1 is released before doing anything

**Comment by legojoshua12** [comment]
As of currently, the installer works perfectly found in this PR for regular Subnautica.  It does not work for Below Zero which has yet to be fixed, so we should wait till 2.1 for a recompile and fix for Below Zero.

**Comment by AlexejheroYTB** [comment]
I think this should be merged as-is, and fix the below zero bug in a new pull request.

**Comment by AlexejheroYTB** [comment]
Closed in favor of #77

**Pull request closed without merging**
